name: Periodic health check

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

jobs:
  health_check:    
    runs-on: ubuntu-latest
    steps:         
      - uses: jtalk/url-health-check-action@v4     
        with: 
          url: https://phonebook-backend-damp-night-5122.fly.dev/
          max-attempts: 2
          retry-delay: 60s